[2025-03-02T00:41:06.418+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: new_messages.messages_load manual__2025-03-02T00:40:50.192529+00:00 [queued]>
[2025-03-02T00:41:06.502+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: new_messages.messages_load manual__2025-03-02T00:40:50.192529+00:00 [queued]>
[2025-03-02T00:41:06.717+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-03-02T00:41:06.936+0000] {taskinstance.py:1382} INFO - Executing <Task(DockerOperator): messages_load> on 2025-03-02 00:40:50.192529+00:00
[2025-03-02T00:41:07.024+0000] {standard_task_runner.py:57} INFO - Started process 1223 to run task
[2025-03-02T00:41:07.055+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'new_messages', 'messages_load', 'manual__2025-03-02T00:40:50.192529+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/mess_cluster.py', '--cfg-path', '/tmp/tmpqxbt3iqh']
[2025-03-02T00:41:07.117+0000] {standard_task_runner.py:85} INFO - Job 31: Subtask messages_load
[2025-03-02T00:41:07.510+0000] {task_command.py:416} INFO - Running <TaskInstance: new_messages.messages_load manual__2025-03-02T00:40:50.192529+00:00 [running]> on host f37df6fae485
[2025-03-02T00:41:08.123+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='new_messages' AIRFLOW_CTX_TASK_ID='messages_load' AIRFLOW_CTX_EXECUTION_DATE='2025-03-02T00:40:50.192529+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-02T00:40:50.192529+00:00'
[2025-03-02T00:41:09.012+0000] {docker.py:367} INFO - Starting docker container from image messages-loader:latest
[2025-03-02T00:46:02.465+0000] {docker.py:438} INFO - ERROR:root:Timeout error: HTTPConnectionPool(host='localhost', port=52635): Read timed out. (read timeout=120)
[2025-03-02T00:48:02.597+0000] {docker.py:438} INFO - INFO:root:News fetched UNsuccessfully.
[2025-03-02T00:49:15.162+0000] {docker.py:438} INFO - INFO:root:News fetched UNsuccessfully.
[2025-03-02T00:49:28.322+0000] {docker.py:438} INFO - INFO:root:News page fetched successfully.
[2025-03-02T00:49:47.422+0000] {docker.py:438} INFO - INFO:root:News fetched UNsuccessfully.
[2025-03-02T00:50:00.770+0000] {docker.py:438} INFO - INFO:root:News page fetched successfully.
[2025-03-02T00:50:13.093+0000] {docker.py:438} INFO - INFO:root:News page fetched successfully.
[2025-03-02T00:50:15.171+0000] {docker.py:438} INFO - [nltk_data] Downloading package stopwords to /root/nltk_data...
[2025-03-02T00:50:15.372+0000] {docker.py:438} INFO - [nltk_data]   Unzipping corpora/stopwords.zip.
[2025-03-02T00:50:16.144+0000] {docker.py:438} INFO - [nltk_data] Downloading package stopwords to /root/nltk_data...
[2025-03-02T00:50:16.161+0000] {docker.py:438} INFO - [nltk_data]   Package stopwords is already up-to-date!
[2025-03-02T00:50:20.832+0000] {docker.py:438} INFO - [nltk_data] Downloading package stopwords to /root/nltk_data...
[2025-03-02T00:50:20.866+0000] {docker.py:438} INFO - [nltk_data]   Package stopwords is already up-to-date!
[2025-03-02T00:50:22.518+0000] {docker.py:438} INFO - [nltk_data] Downloading package stopwords to /root/nltk_data...
[2025-03-02T00:50:22.520+0000] {docker.py:438} INFO - [nltk_data]   Package stopwords is already up-to-date!
[2025-03-02T00:50:22.746+0000] {docker.py:438} INFO - [nltk_data] Downloading package stopwords to /root/nltk_data...
[2025-03-02T00:50:22.751+0000] {docker.py:438} INFO - [nltk_data]   Package stopwords is already up-to-date!
[2025-03-02T00:50:24.105+0000] {docker.py:438} INFO - [nltk_data] Downloading package stopwords to /root/nltk_data...
[2025-03-02T00:50:24.113+0000] {docker.py:438} INFO - [nltk_data]   Package stopwords is already up-to-date!
[2025-03-02T00:50:25.351+0000] {docker.py:438} INFO - [nltk_data] Downloading package stopwords to /root/nltk_data...
[2025-03-02T00:50:25.352+0000] {docker.py:438} INFO - [nltk_data]   Package stopwords is already up-to-date!
[2025-03-02T00:50:25.963+0000] {docker.py:438} INFO - [nltk_data] Downloading package stopwords to /root/nltk_data...
[2025-03-02T00:50:25.966+0000] {docker.py:438} INFO - [nltk_data]   Package stopwords is already up-to-date!
[2025-03-02T00:50:26.176+0000] {docker.py:438} INFO - [nltk_data] Downloading package stopwords to /root/nltk_data...
[2025-03-02T00:50:26.240+0000] {docker.py:438} INFO - [nltk_data]   Package stopwords is already up-to-date!
[2025-03-02T00:50:26.719+0000] {docker.py:438} INFO - [nltk_data] Downloading package stopwords to /root/nltk_data...
[2025-03-02T00:50:26.722+0000] {docker.py:438} INFO - [nltk_data]   Package stopwords is already up-to-date!
[2025-03-02T00:50:27.242+0000] {docker.py:438} INFO - [nltk_data] Downloading package stopwords to /root/nltk_data...
[2025-03-02T00:50:27.243+0000] {docker.py:438} INFO - [nltk_data]   Package stopwords is already up-to-date!
[2025-03-02T00:50:27.605+0000] {docker.py:438} INFO - [nltk_data] Downloading package stopwords to /root/nltk_data...
[2025-03-02T00:50:27.645+0000] {docker.py:438} INFO - [nltk_data]   Package stopwords is already up-to-date!
[2025-03-02T00:50:27.745+0000] {docker.py:438} INFO - [nltk_data] Downloading package stopwords to /root/nltk_data...
[2025-03-02T00:50:27.746+0000] {docker.py:438} INFO - [nltk_data]   Package stopwords is already up-to-date!
[2025-03-02T00:50:28.943+0000] {docker.py:438} INFO - [nltk_data] Downloading package stopwords to /root/nltk_data...
[2025-03-02T00:50:28.947+0000] {docker.py:438} INFO - [nltk_data]   Package stopwords is already up-to-date!
[2025-03-02T00:50:29.294+0000] {docker.py:438} INFO - [nltk_data] Downloading package stopwords to /root/nltk_data...
[2025-03-02T00:50:29.295+0000] {docker.py:438} INFO - [nltk_data]   Package stopwords is already up-to-date!
[2025-03-02T00:50:29.526+0000] {docker.py:438} INFO - [nltk_data] Downloading package stopwords to /root/nltk_data...
[2025-03-02T00:50:29.528+0000] {docker.py:438} INFO - [nltk_data]   Package stopwords is already up-to-date!
[2025-03-02T00:50:30.091+0000] {docker.py:438} INFO - [nltk_data] Downloading package stopwords to /root/nltk_data...
[2025-03-02T00:50:30.094+0000] {docker.py:438} INFO - [nltk_data]   Package stopwords is already up-to-date!
[2025-03-02T00:50:30.266+0000] {docker.py:438} INFO - [nltk_data] Downloading package stopwords to /root/nltk_data...
[2025-03-02T00:50:30.268+0000] {docker.py:438} INFO - [nltk_data]   Package stopwords is already up-to-date!
[2025-03-02T00:50:30.401+0000] {docker.py:438} INFO - [nltk_data] Downloading package stopwords to /root/nltk_data...
[2025-03-02T00:50:30.410+0000] {docker.py:438} INFO - [nltk_data]   Package stopwords is already up-to-date!
[2025-03-02T00:50:30.957+0000] {docker.py:438} INFO - [nltk_data] Downloading package stopwords to /root/nltk_data...
[2025-03-02T00:50:30.961+0000] {docker.py:438} INFO - [nltk_data]   Package stopwords is already up-to-date!
[2025-03-02T00:50:31.443+0000] {docker.py:438} INFO - [nltk_data] Downloading package stopwords to /root/nltk_data...
[2025-03-02T00:50:31.453+0000] {docker.py:438} INFO - [nltk_data]   Package stopwords is already up-to-date!
[2025-03-02T00:50:31.584+0000] {docker.py:438} INFO - [nltk_data] Downloading package stopwords to /root/nltk_data...
[2025-03-02T00:50:31.586+0000] {docker.py:438} INFO - [nltk_data]   Package stopwords is already up-to-date!
[2025-03-02T00:50:35.483+0000] {docker.py:438} INFO - [nltk_data] Downloading package stopwords to /root/nltk_data...
[2025-03-02T00:50:35.502+0000] {docker.py:438} INFO - [nltk_data]   Package stopwords is already up-to-date!
[2025-03-02T00:50:36.166+0000] {docker.py:438} INFO - [nltk_data] Downloading package stopwords to /root/nltk_data...
[2025-03-02T00:50:36.168+0000] {docker.py:438} INFO - [nltk_data]   Package stopwords is already up-to-date!
[2025-03-02T00:50:36.384+0000] {docker.py:438} INFO - [nltk_data] Downloading package stopwords to /root/nltk_data...
[2025-03-02T00:50:36.385+0000] {docker.py:438} INFO - [nltk_data]   Package stopwords is already up-to-date!
[2025-03-02T00:50:36.692+0000] {docker.py:438} INFO - [nltk_data] Downloading package stopwords to /root/nltk_data...
[2025-03-02T00:50:36.716+0000] {docker.py:438} INFO - [nltk_data]   Package stopwords is already up-to-date!
[2025-03-02T00:50:36.983+0000] {docker.py:438} INFO - [nltk_data] Downloading package stopwords to /root/nltk_data...
[2025-03-02T00:50:36.986+0000] {docker.py:438} INFO - [nltk_data]   Package stopwords is already up-to-date!
[2025-03-02T00:50:37.316+0000] {docker.py:438} INFO - [nltk_data] Downloading package stopwords to /root/nltk_data...
[2025-03-02T00:50:37.318+0000] {docker.py:438} INFO - [nltk_data]   Package stopwords is already up-to-date!
[2025-03-02T00:50:37.713+0000] {docker.py:438} INFO - [nltk_data] Downloading package stopwords to /root/nltk_data...
[2025-03-02T00:50:37.716+0000] {docker.py:438} INFO - [nltk_data]   Package stopwords is already up-to-date!
[2025-03-02T00:50:38.376+0000] {docker.py:438} INFO - [nltk_data] Downloading package stopwords to /root/nltk_data...
[2025-03-02T00:50:38.381+0000] {docker.py:438} INFO - [nltk_data]   Package stopwords is already up-to-date!
[2025-03-02T00:50:38.787+0000] {docker.py:438} INFO - Traceback (most recent call last):
[2025-03-02T00:50:38.790+0000] {docker.py:438} INFO -   File "/workdir/Parsing.py", line 168, in <module>
[2025-03-02T00:50:38.791+0000] {docker.py:438} INFO - load_data()
[2025-03-02T00:50:38.798+0000] {docker.py:438} INFO - File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1161, in __call__
[2025-03-02T00:50:38.820+0000] {docker.py:438} INFO - return self.main(*args, **kwargs)
[2025-03-02T00:50:38.822+0000] {docker.py:438} INFO - ^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-03-02T00:50:38.824+0000] {docker.py:438} INFO -   File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1082, in main
[2025-03-02T00:50:38.828+0000] {docker.py:438} INFO - rv = self.invoke(ctx)
[2025-03-02T00:50:38.828+0000] {docker.py:438} INFO - ^^^^^^^^^^^^^^^^
[2025-03-02T00:50:38.830+0000] {docker.py:438} INFO -   File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1443, in invoke
[2025-03-02T00:50:38.836+0000] {docker.py:438} INFO - return ctx.invoke(self.callback, **ctx.params)
[2025-03-02T00:50:38.838+0000] {docker.py:438} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-03-02T00:50:38.838+0000] {docker.py:438} INFO -   File "/usr/local/lib/python3.12/site-packages/click/core.py", line 788, in invoke
[2025-03-02T00:50:38.840+0000] {docker.py:438} INFO - return __callback(*args, **kwargs)
[2025-03-02T00:50:38.844+0000] {docker.py:438} INFO - ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-03-02T00:50:38.853+0000] {docker.py:438} INFO - File "/workdir/Parsing.py", line 163, in load_data
[2025-03-02T00:50:38.854+0000] {docker.py:438} INFO - df.to_csv(data_path, index=False)
[2025-03-02T00:50:38.858+0000] {docker.py:438} INFO - File "/usr/local/lib/python3.12/site-packages/pandas/util/_decorators.py", line 333, in wrapper
[2025-03-02T00:50:38.861+0000] {docker.py:438} INFO - return func(*args, **kwargs)
[2025-03-02T00:50:38.865+0000] {docker.py:438} INFO - ^^^^^^^^^^^^^^^^^^^^^
[2025-03-02T00:50:38.868+0000] {docker.py:438} INFO - File "/usr/local/lib/python3.12/site-packages/pandas/core/generic.py", line 3967, in to_csv
[2025-03-02T00:50:38.872+0000] {docker.py:438} INFO - return DataFrameRenderer(formatter).to_csv(
[2025-03-02T00:50:38.876+0000] {docker.py:438} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-03-02T00:50:38.882+0000] {docker.py:438} INFO - File "/usr/local/lib/python3.12/site-packages/pandas/io/formats/format.py", line 1014, in to_csv
[2025-03-02T00:50:38.889+0000] {docker.py:438} INFO - csv_formatter.save()
[2025-03-02T00:50:38.897+0000] {docker.py:438} INFO -   File "/usr/local/lib/python3.12/site-packages/pandas/io/formats/csvs.py", line 251, in save
[2025-03-02T00:50:38.899+0000] {docker.py:438} INFO - with get_handle(
[2025-03-02T00:50:38.900+0000] {docker.py:438} INFO -          ^^^^^^^^^^^
[2025-03-02T00:50:38.901+0000] {docker.py:438} INFO -   File "/usr/local/lib/python3.12/site-packages/pandas/io/common.py", line 749, in get_handle
[2025-03-02T00:50:38.903+0000] {docker.py:438} INFO - check_parent_directory(str(handle))
[2025-03-02T00:50:38.905+0000] {docker.py:438} INFO - File "/usr/local/lib/python3.12/site-packages/pandas/io/common.py", line 616, in check_parent_directory
[2025-03-02T00:50:38.910+0000] {docker.py:438} INFO - raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
[2025-03-02T00:50:38.911+0000] {docker.py:438} INFO - OSError: Cannot save file into a non-existent directory: '/opt/***/data/raw'
[2025-03-02T00:50:42.533+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/docker/operators/docker.py", line 513, in execute
    return self._run_image()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/docker/operators/docker.py", line 384, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/docker/operators/docker.py", line 446, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 1}
[2025-03-02T00:50:42.646+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=new_messages, task_id=messages_load, execution_date=20250302T004050, start_date=20250302T004106, end_date=20250302T005042
[2025-03-02T00:50:42.853+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 31 for task messages_load (Docker container failed: {'StatusCode': 1}; 1223)
[2025-03-02T00:50:42.909+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-03-02T00:50:43.154+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
